source 'https://rubygems.org'

gem 'clearbit'
gem 'plaid'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'tilt-jbuilder', '>= 0.4.0', require: 'sinatra/jbuilder'

group :development, :test do
  gem 'pry'
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'vcr'
  gem 'webmock'
end
